// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvIF7_isBVlj9oTkweUittmeMTK2V5xts',
    appId: '1:1019219772775:web:cfe77ff10b50ff28f49bc2',
    messagingSenderId: '1019219772775',
    projectId: 'nirbhaya-2006',
    authDomain: 'nirbhaya-2006.firebaseapp.com',
    storageBucket: 'nirbhaya-2006.firebasestorage.app',
    measurementId: 'G-5S02ZGESNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLzQuogfzrnlm9gQrLPE9lKmxZGfC28yw',
    appId: '1:1019219772775:android:517e15d8516c1eb6f49bc2',
    messagingSenderId: '1019219772775',
    projectId: 'nirbhaya-2006',
    storageBucket: 'nirbhaya-2006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG_uAoEHmuVWdElRbS73g4ydNx3Ozskj4',
    appId: '1:1019219772775:ios:5021b71997825dadf49bc2',
    messagingSenderId: '1019219772775',
    projectId: 'nirbhaya-2006',
    storageBucket: 'nirbhaya-2006.firebasestorage.app',
    iosBundleId: 'com.example.safetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG_uAoEHmuVWdElRbS73g4ydNx3Ozskj4',
    appId: '1:1019219772775:ios:5021b71997825dadf49bc2',
    messagingSenderId: '1019219772775',
    projectId: 'nirbhaya-2006',
    storageBucket: 'nirbhaya-2006.firebasestorage.app',
    iosBundleId: 'com.example.safetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvIF7_isBVlj9oTkweUittmeMTK2V5xts',
    appId: '1:1019219772775:web:1ce18c369bc62062f49bc2',
    messagingSenderId: '1019219772775',
    projectId: 'nirbhaya-2006',
    authDomain: 'nirbhaya-2006.firebaseapp.com',
    storageBucket: 'nirbhaya-2006.firebasestorage.app',
    measurementId: 'G-SGMMNZLV3W',
  );
}
